// Code generated by "stringer -type Action -trimprefix Action"; DO NOT EDIT.

package combat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionInvalid-0]
	_ = x[ActionStab-1]
	_ = x[ActionSlash-2]
	_ = x[ActionCrush-3]
	_ = x[ActionCast-4]
	_ = x[ActionFire-5]
	_ = x[ActionDefend-6]
	_ = x[ActionEquip-7]
	_ = x[ActionAttack-8]
	_ = x[ActionDie-9]
}

const _Action_name = "InvalidStabSlashCrushCastFireDefendEquipAttackDie"

var _Action_index = [...]uint8{0, 7, 11, 16, 21, 25, 29, 35, 40, 46, 49}

func (i Action) String() string {
	if i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
