// Code generated by "stringer -type Splat -trimprefix Splat"; DO NOT EDIT.

package combat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SplatMiss-0]
	_ = x[SplatHit-1]
	_ = x[SplatPoison-2]
}

const _Splat_name = "MissHitPoison"

var _Splat_index = [...]uint8{0, 4, 7, 13}

func (i Splat) String() string {
	if i >= Splat(len(_Splat_index)-1) {
		return "Splat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Splat_name[_Splat_index[i]:_Splat_index[i+1]]
}
