// Code generated by "stringer -type Style -trimprefix Style"; DO NOT EDIT.

package combat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StyleInvalid-0]
	_ = x[StyleAccurate-1]
	_ = x[StyleAggressive-2]
	_ = x[StyleDefensive-3]
	_ = x[StyleControlled-4]
	_ = x[StyleRapid-5]
	_ = x[StyleLongrange-6]
	_ = x[StyleMagic-7]
	_ = x[StyleAutocast-8]
}

const _Style_name = "InvalidAccurateAggressiveDefensiveControlledRapidLongrangeMagicAutocast"

var _Style_index = [...]uint8{0, 7, 15, 25, 34, 44, 49, 58, 63, 71}

func (i Style) String() string {
	if i >= Style(len(_Style_index)-1) {
		return "Style(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Style_name[_Style_index[i]:_Style_index[i+1]]
}
